from collections.abc import Iterable, Sequence
from typing import final, overload

import polars as pl

@final
class PySecurityAxis:
    def __len__(self, /) -> int: ...
    def __new__(cls, /, keys: Sequence[str]) -> PySecurityAxis: ...
    def __repr__(self, /) -> str: ...
    def keys(self, /) -> list[str]: ...
    def take(self, /, indices: Sequence[int]) -> PySecurityAxis: ...

@final
class PyUniverseMapping:
    def __add__(self, /, rhs: PyUniverseMapping | float) -> PyUniverseMapping: ...
    @overload
    def __getitem__(self, /, key: str) -> float: ...
    @overload
    def __getitem__(self, /, key: pl.Series | Iterable[str]) -> pl.Series: ...
    def __len__(self, /) -> int: ...
    def __mul__(self, /, rhs: PyUniverseMapping | float) -> PyUniverseMapping: ...
    def __new__(
        cls, /, keys: Sequence[str], values: Sequence[float]
    ) -> PyUniverseMapping: ...
    def __radd__(self, /, rhs: PyUniverseMapping | float) -> PyUniverseMapping: ...
    def __repr__(self, /) -> str: ...
    def __rmul__(self, /, rhs: PyUniverseMapping | float) -> PyUniverseMapping: ...
    def __rsub__(self, /, rhs: PyUniverseMapping | float) -> PyUniverseMapping: ...
    def __rtruediv__(self, /, rhs: PyUniverseMapping | float) -> PyUniverseMapping: ...
    def __sub__(self, /, rhs: PyUniverseMapping | float) -> PyUniverseMapping: ...
    def __truediv__(self, /, rhs: PyUniverseMapping | float) -> PyUniverseMapping: ...
    @staticmethod
    def from_axis(
        axis: PySecurityAxis, values: Sequence[float]
    ) -> PyUniverseMapping: ...
    @staticmethod
    def from_series(axis: PySecurityAxis, series: pl.Series) -> PyUniverseMapping: ...
    def keys(self, /) -> list[str]: ...
    def sum(self, /) -> float: ...
    def values(self, /) -> pl.Series: ...
