from collections.abc import Iterable
from typing import overload

def sum_as_string(a: int, b: int) -> str: ...

class PySecurityAxis:
    def __init__(self, keys: tuple[str, ...] | list[str]) -> None: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def keys(self) -> list[str]: ...
    def take(self, indices: list[int]) -> PySecurityAxis: ...

class PyUniverseMapping:
    def __init__(self, keys: list[str], values: list[float]) -> None: ...
    @staticmethod
    def from_axis(axis: PySecurityAxis, values: list[float]) -> PyUniverseMapping: ...
    @staticmethod
    def from_series(axis: PySecurityAxis, series: object) -> PyUniverseMapping: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, key: str) -> float: ...
    @overload
    def __getitem__(self, key: Iterable[str]) -> object: ...
    def __getitem__(self, key: str | Iterable[str]) -> float | object: ...
    def __add__(self, other: PyUniverseMapping | int | float) -> PyUniverseMapping: ...
    def __radd__(self, other: PyUniverseMapping | int | float) -> PyUniverseMapping: ...
    def __sub__(self, other: PyUniverseMapping | int | float) -> PyUniverseMapping: ...
    def __rsub__(self, other: PyUniverseMapping | int | float) -> PyUniverseMapping: ...
    def __mul__(self, other: PyUniverseMapping | int | float) -> PyUniverseMapping: ...
    def __rmul__(self, other: PyUniverseMapping | int | float) -> PyUniverseMapping: ...
    def __truediv__(
        self, other: PyUniverseMapping | int | float
    ) -> PyUniverseMapping: ...
    def __rtruediv__(
        self, other: PyUniverseMapping | int | float
    ) -> PyUniverseMapping: ...
    def __repr__(self) -> str: ...
    def keys(self) -> list[str]: ...
    def values(self) -> object: ...
    def sum(self) -> float: ...
