from _typeshed import Incomplete
from collections.abc import Sequence
from typing import Any, final

@final
class PySecurityAxis:
    def __len__(self, /) -> int: ...
    def __new__(cls, /, keys: Sequence[str]) -> PySecurityAxis: ...
    def __repr__(self, /) -> str: ...
    def keys(self, /) -> list[str]: ...
    def take(self, /, indices: Sequence[int]) -> PySecurityAxis: ...

@final
class PyUniverseMapping:
    def __add__(self, /, rhs: PyUniverseMapping |float) -> PyUniverseMapping: ...
    def __getitem__(self, /, key: Any) -> Any: ...
    def __len__(self, /) -> int: ...
    def __mul__(self, /, rhs: PyUniverseMapping |float) -> PyUniverseMapping: ...
    def __new__(cls, /, keys: Sequence[str], values: Sequence[float]) -> PyUniverseMapping: ...
    def __radd__(self, /, rhs: PyUniverseMapping |float) -> PyUniverseMapping: ...
    def __repr__(self, /) -> str: ...
    def __rmul__(self, /, rhs: PyUniverseMapping |float) -> PyUniverseMapping: ...
    def __rsub__(self, /, rhs: PyUniverseMapping |float) -> PyUniverseMapping: ...
    def __rtruediv__(self, /, rhs: PyUniverseMapping |float) -> PyUniverseMapping: ...
    def __sub__(self, /, rhs: PyUniverseMapping |float) -> PyUniverseMapping: ...
    def __truediv__(self, /, rhs: PyUniverseMapping |float) -> PyUniverseMapping: ...
    @staticmethod
    def from_axis(axis: PySecurityAxis, values: Sequence[float]) -> PyUniverseMapping: ...
    @staticmethod
    def from_series(axis: PySecurityAxis, series: Incomplete) -> PyUniverseMapping: ...
    def keys(self, /) -> list[str]: ...
    def sum(self, /) -> float: ...
    def values(self, /) -> Incomplete: ...

def sum_as_string(a: int, b: int) -> str: ...
